Fixes #2616. Support combining sequences that don't normalize.
tui-cs/Terminal.Gui pull request #3877
Opened 2024-12-03 04:22 UTC by BDisp

## Fixes

- Fixes #2616

## Proposed Changes/Todos

- [x] Using `WindowsDriver` only works on Windows Terminal Preview

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

2024-12-05 00:59 UTC, BDisp commented
![image](https://github.com/user-attachments/assets/b841a5d6-fb5f-4764-a9a9-3b086789b676)

2024-12-05 15:51 UTC, tig requested changes

2024-12-05 15:51 UTC, tig commented on Terminal.Gui/ConsoleDrivers/ConsoleDriver.cs
> +                            //if (Col < clipRect.Right - 1)
This is a pretty important case. I'm not sure why it's revoved.

2024-12-05 22:43 UTC, tig commented
This is awesome.

Can you help figure out why charmap is doing this?

![Tq8hSSN 1](https://github.com/user-attachments/assets/a5193bc6-84da-430a-a098-ae10e89897c5)

2024-12-05 23:11 UTC, BDisp commented
The `WindowsDriver` it's more harder to deal because it's using a buffer instead of rows and columns like the other drivers. it's needed to add space  characters to fill the gaps generated in the columns. It's giving much more work and I couldn't yet figure out the way to fix it.

2024-12-05 23:17 UTC, BDisp commented
I think the better solution for the charmap is to use views with a width of 2 and a height of 1 for all glyphs. Thus it isn't needed to manipulate the column width of the runes. Also all the views are aligned with each other. What do you think?

2024-12-05 23:31 UTC, tig commented
> I think the better solution for the charmap is to use views with a width of 2 and a height of 1 for all glyphs. Thus it isn't needed to manipulate the column width of the runes. Also all the views are aligned with each other. What do you think?

No, that would just mask the issue. 

I'd rather us figure out how to fix Windows driver.

2024-12-07 18:55 UTC, BDisp commented
This approach and the existent one have a real issue when a combining mark is set in the `View.Text` and the previous rune don't belong to this view. For e.g. if the previous rune belong to label and it's an 'a' starting inserting an '\u0301' in the `View.Text`, the driver will write 'á' instead of "a´". So, we need to think a better solution to add combining marks. I'll try find a more appropriate solution.

2024-12-08 01:52 UTC, tig commented
> This approach and the existent one have a real issue when a combining mark is set in the `View.Text` and the previous rune don't belong to this view. For e.g. if the previous rune belong to label and it's an 'a' starting inserting an '\u0301' in the `View.Text`, the driver will write 'á' instead of "a´". So, we need to think a better solution to add combining marks. I'll try find a more appropriate solution.

This is precisely why I started down the Cell route way back. 

We need to create an abstraction that lets us keep track of what the user/dev intended and then ensure the driver (where each platform behaves differently) gets the right chars in the right spot.

2024-12-08 01:55 UTC, tig commented
This is relevant: https://github.com/gui-cs/Terminal.Gui/issues/2933

Particularly the links near end of discussion.

2024-12-08 15:44 UTC, tznind commented
If possible can you please think about how we will integrate these changes into the v2 drivers refactoring branch too.  I've copied much of this code you are changing to the WindowsOut class.

2024-12-08 17:36 UTC, BDisp commented
> If possible can you please think about how we will integrate these changes into the v2 drivers refactoring branch too. I've copied much of this code you are changing to the WindowsOutput class.

That's good, this way you can check if it's working as expected in the new v2 drivers. I haven't yet resolves all the glyphs handling which I still try to found how to deal with some situations. But when I've this almost finished I'll to see how it can be integrated. `WindowsDriver` is giving some more work and I really seriously thinking using a for loop for rows and cols in the write to console instead of a foreach, unless I figure that I can deal well to find each last column.

2024-12-13 19:28 UTC, BDisp commented
I already ran the `ShowTopLine_True_TabsOnBottom_False_With_Unicode` unit test in Linux and Mac and it pass on both. So, I've no idea about it's going on here.

```
Passed Terminal.Gui.ViewsTests.TabViewTests.RemoveTab_ChangesSelection [2 ms]
[xUnit.net 00:01:34.23]     Terminal.Gui.ViewsTests.TabViewTests.ShowTopLine_True_TabsOnBottom_False_With_Unicode [FAIL]
[xUnit.net 00:01:34.23]       Assert.Equal() Failure: Strings differ
[xUnit.net 00:01:34.23]                                          ↓ (pos 29)
[xUnit.net 00:01:34.23]       Expected: ···"──────╮    \n│Les Misérables│    \n◄       "···
 │hi2               │
 └──────────────────┘
  But Was:
 ╭──────────────╮    
 │Les Miserables│    
 ◄              ╰───╮
 │hi2               │
 └──────────────────┘



Test Run Failed.
Total tests: 10312
     Passed: 10289
     Failed: 1
    Skipped: 22
 Total time: 2.0031 Minutes
       _VSTestConsole:
         MSB4181: The "VSTestTask" task returned false but did not log an error.
     8>Done Building Project "/home/runner/work/Terminal.Gui/Terminal.Gui/UnitTests/UnitTests.csproj" (VSTest target(s)) -- FAILED.
     1>Done Building Project "/home/runner/work/Terminal.Gui/Terminal.Gui/Terminal.sln" (VSTest target(s)) -- FAILED.

```

2025-09-27 14:00 UTC, closed without merging